### ISSUE TITLE
stage0

### ISSUE THREAD

**Issue by VincentWangty** [yiren-jian/BLIText#3]
thanks for your work, could you commit the config of stage0?

**Comment by yiren-jian** [comment]
stage0 training [log](https://github.com/yiren-jian/BLIText/blob/main/training_logs/BLIP-T/training_stage0.txt) (which you can use as reference to create your config yaml) is uploaded. I will later update the pretrained models as well.

The training was on a remote server with 3x RTX-A6000.

**Comment by VincentWangty** [comment]
> stage0 training [log](https://github.com/yiren-jian/BLIText/blob/main/training_logs/BLIP-T/training_stage0.txt) (which you can use as reference to create your config yaml) is uploaded. I will later update the pretrained models as well.
> 
> The training was on a remote server with 3x RTX-A6000.

thx!
