### ISSUE TITLE
For Reproducing the Video Experiments

### ISSUE THREAD

**Issue by NingMa-AI** [yiren-jian/BLIText#4]
Hi, Dr. Jian:
     Glad to see your interesting work. I want to reproduce the video part experiments but can not find the related introduction and script. Could you do me a favor providing related clues? 

    Best,
    Ma Ning, Post-Doc Fellow at HKUST
    E-mail: csemaning@ust.hk or ma_ning@zju.edu.cn

**Comment by yiren-jian** [comment]
I created a new repo: https://github.com/yiren-jian/BLIText-video, 

There are new `dataset`, `build dataloader` and `model files`. Configuration files are stored in `lavis/projects/blip2/train`.   I'm sorry if you find the code messy.

**Comment by NingMa-AI** [comment]
Excellent! Appreciate your response!
